categories: [Sequence Analysis]
description: Functional ANnoTAtion based on embedding space SImilArity
homepage_url: https://github.com/MetazoaPhylogenomicsLab/FANTASIA
long_description: | 
    Fantasia is a pipeline for annotating GO terms in protein sequence file 
    using GOPredSim with the protein language model ProtT5.
owner: genouest
name: fantasia
remote_repository_url: https://github.com/genouest/galaxy-tools/tree/master/tools/fantasia
