categories: [Genome annotation]
description: BRAKER3 is a pipeline for fully automated prediction of protein coding gene structures with GeneMark-ES/ET and AUGUSTUS in novel eukaryotic genomes .
homepage_url: https://github.com/Gaius-Augustus/BRAKER
long_description: BRAKER3 is a pipeline for fully automated prediction of protein coding gene structures with GeneMark-ES/ET and AUGUSTUS in novel eukaryotic genomes .
owner: genouest
name: braker3
remote_repository_url: https://github.com/genouest/galaxy-tools/tree/master/tools/braker
type: unrestricted
