categories:
- Genome annotation
description: Run Enzbert model 
long_description: |
  This tool runs Enzbert model.
name: enzbert
owner: genouest
remote_repository_url: https://github.com/genouest/galaxy-tools/tree/main/tools/enzbert
type: unrestricted
homepage_url: https://gitlab.inria.fr/nbuton/tfpc/-/tree/EnzBert_conda
